at1/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include(('users.urls', 'users'), namespace='users')),
    path('eduprod/', include(('eduprod.urls', 'eduprod'), namespace='eduprod')),
    path('accounts/login/', include('users.urls')),
]

eduprod/urls.py
from django.urls import path
from .views import QuestionCreate, QuestionUpdate, QuestionDelete, QuestionList
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('question/add/', QuestionCreate.as_view(), name='question_add'),
    path('question/<int:pk>/edit/', QuestionUpdate.as_view(), name='question_edit'),
    path('question/<int:pk>/delete/', QuestionDelete.as_view(), name='question_delete'),
    path('questions/', QuestionList.as_view(), name='question_list'),
]

users/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
]

eduprod/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import gettext_lazy as _

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    answer_text = models.TextField()
    category = models.CharField(max_length=50, default='General')  # Adding the 'category' field

    def __str__(self):
        return self.question_text

users/models.py
from django.db import models

# Create your models here.

eduprod/forms.py
from django import forms
from .models import Question

class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ['question_text', 'answer_text']

eduprod/views.py
import random
from django.core import serializers
from django.shortcuts import render
from .models import Question
from django.db.models import OuterRef, Subquery, Count
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import QuestionForm
from django.views.generic.list import ListView
from django.contrib.auth.decorators import login_required

@login_required
def index(request):
    # Get the first and last question ID
    first_id = Question.objects.order_by('id').first().id
    last_id = Question.objects.order_by('id').last().id

##Randomising Questions##
    # Initialize an array to store unique question IDs
    random_ids = []
    # Generate 5 unique random question IDs
    while len(random_ids) < 5:
        random_id = random.randint(first_id, last_id)
        # Check if the random ID matches an existing question ID and is not already in the array
        if Question.objects.filter(id=random_id).exists() and random_id not in random_ids:
            random_ids.append(random_id)
    # Retrieve the questions matching the random IDs
    questions = Question.objects.filter(id__in=random_ids)
    # Serialize the questions to JSON
    questions_json = serializers.serialize('json', questions)

##Retrieve Question Categories##
    # Get distinct categories for all questions
    categories = Question.objects.values_list('category', flat=True).distinct()

##Pass the Data to index.html##
    context = {
        'questions_json': questions_json,
        'categories': categories
    }
    return render(request, 'eduprod/index.html', context)

class QuestionCreate(LoginRequiredMixin, CreateView):
    model = Question
    form_class = QuestionForm
    template_name = 'eduprod/question_form.html'
    success_url = reverse_lazy('eduprod:question_list')  # Redirect to the question list page after creating

class QuestionUpdate(LoginRequiredMixin, UpdateView):
    model = Question
    form_class = QuestionForm
    template_name = 'eduprod/question_form.html'
    success_url = reverse_lazy('eduprod:question_list')  # Redirect to the question list page after updating

class QuestionDelete(LoginRequiredMixin, DeleteView):
    model = Question
    template_name = 'eduprod/question_confirm_delete.html'
    success_url = reverse_lazy('eduprod:question_list')  # Redirect to the question list page after deleting

class QuestionList(LoginRequiredMixin, ListView):
    model = Question
    context_object_name = 'questions'
    template_name = 'eduprod/question_list.html'

users/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages

def index(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("users:login"))
    return render(request, "users/user.html")

def login_view(request):
    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("users:index"))
        else:
            messages.success(request, "Invalid Credentials.")
            return render(request, "users/login.html")
    return render(request, "users/login.html")

def logout_view(request):
    logout(request)
    messages.success(request, "Successfully logged out.")
    return redirect(reverse('users:login'))

eduprod/templates/eduprod/index.html
{% extends "eduprod/layout.html" %}
{% block body %}
<!--Question-->
<div id="content" data-questions='{{ questions_json }}'></div>
<!--Answer Button-->
<button id="revealBtn">Reveal Answer</button>
<form action="{% url 'eduprod:index' %}" method="post" style="margin: 0; margin-left: 20px;">
    {% csrf_token %}
    <button type="submit">Reset Quiz</button>
</form>
<br></br>
<!-- Dropdown menu for selecting categories -->
<select id="categorySelect">
    <option value="all">All Categories</option>
    {% for category in categories %}
        <option value="{{ category }}">{{ category }}</option>
    {% endfor %}
</select>
<br></br>
<!-- Add Question Link -->
<div style="margin-top: 20px;">
    <a href="{% url 'eduprod:question_add' %}">Add a new question</a>
</div>
<!-- Link to Question List for Editing or Deleting Questions -->
<div style="margin-top: 10px;">
    <a href="{% url 'eduprod:question_list' %}">Manage questions</a>
</div>

{% endblock %}

eduprod/templates/eduprod/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Q&A</title>
    <link href="{% static 'eduprod/styles.css' %}" rel="stylesheet">
    <script src="{% static 'eduprod/scripts.js' %}" defer></script>
</head>
<body>
    <div class="header">
        <div class="logo">
            <img src="{% static 'users/logo.gif' %}" alt="Logo">
        </div>
        <div class="user-info">
            <span>{{ user.username }}</span>
            <form action="{% url 'users:logout' %}" method="post" style="margin: 0; margin-left: 20px;">
                {% csrf_token %}
                <button type="submit">Log out</button>
            </form>
        </div>
    </div>   
    <br></br>
    {% if messages %}
        <ul class="messages">
        {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
        </ul>
    {% endif %}    
    {% block body %}
    {% endblock %}
</body>
</html>

eduprod/templates/eduprod/question_confirm_delete.html
{% extends "eduprod/layout.html" %}
{% block body %}
<h2>Are you sure you want to delete "{{ object }}"?</h2>
<form method="post">
    {% csrf_token %}
    <button type="submit"> Confirm </button>
</form>
</br></br>
<a href="{% url 'eduprod:index'%}">Go back</a>
{% endblock %}

eduprod/templates/eduprod/question_form.html
{% extends "eduprod/layout.html" %}
{% block body %}
<h2>{% if object %}Edit Question{% else %}Add Question{% endif %}</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save</button>
</form>
</br></br>
<a href="{% url 'eduprod:index'%}">Go back</a>
{% endblock %}

eduprod/templates/eduprod/question_list.html
{% extends "eduprod/layout.html" %}
{% block body %}
<h2>Questions</h2>
<table>
    {% for question in questions %}
    <tr><td style="text-align:right;">
            {{ question.question_text }} ({{ question.answer_text }})
        </td>
        <td>
            <a href="{% url 'eduprod:question_edit' question.id %}">Edit</a>
        </td>
        <td>
            <a href="{% url 'eduprod:question_delete' question.id %}">Delete</a>
        </td>
    </td></tr>
    {% endfor %}
</table>
<a href="{% url 'eduprod:question_add' %}">Add a new question</a>
<br></br>
<a href="{% url 'eduprod:index'%}">Go back</a>
{% endblock %}

users/templates/users/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Q&A</title>
    <link href="{% static 'users/styles.css' %}" rel="stylesheet">
</head>
<body>
    <div class="header">
        <div class="logo">
            <img src="{% static 'users/logo.gif' %}" alt="Logo">
        </div>
        <div class="user-info">
            <span>{{ user.username }}</span>
            <form action="{% url 'users:logout' %}" method="post" style="margin: 0; margin-left: 20px;">
                {% csrf_token %}
                <button type="submit">Log out</button>
            </form>
        </div>
    </div>   
    {% if messages %}
        <ul class="messages">
        {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
        </ul>
    {% endif %}
    {% block body %}
    {% endblock %}
</body>
</html>

users/templates/users/login.html
{% extends "users/layout.html" %}
{% block body %}
<form action="{% url 'users:login' %}" method="post">
    {% csrf_token %}
    <input type="text" name="username" placeholder="Username">
    <input type="password" name="password" placeholder="Password">
    <input type="submit" value="Login">
</form>
{% endblock %}

users/templates/users/user.html
{% extends "users/layout.html" %}
{% block body %}
    <h1>Welcome, {{ request.user.first_name }}</h1>
    <p>Username: {{ request.user.username }}</p>
    <a href="{% url 'eduprod:index' %}">Take the Quiz</a>
{% endblock %}






    